### ISSUE TITLE
Use cases for this project?

### ISSUE THREAD

**Issue by KyleAMathews** [kapetan/text-height#1]
Doing some research about how to improve typography in browsers through the magic of Javascript and this looks like a useful tool.

Curious how you're using it and other possible use cases you see.

**Comment by kapetan** [comment]
I'm currently playing around with drawing text on a canvas. I'm trying to draw text of different fonts and sizes on the same line, and use this module to calculate the height of the text so I can align it according its baseline, similar how the `vertical-align: baseline;` works in css. 

I also use [text-width](https://github.com/kapetan/text-width) to do word wrapping.

**Comment by KyleAMathews** [comment]
ah interesting. I've been been trying to figure out ways to improve normal text layout along lines of this article http://www.smashingmagazine.com/2012/12/17/css-baseline-the-good-the-bad-and-the-ugly/. Right now to do this you need to make manual adjustments for each font you use depending on its various measurements so it'd be cool if you could make automatic adjustments with a tool like this.

I assume you've seen https://github.com/Flipboard/react-canvas? They're attacking similar problems.

**Comment by kapetan** [comment]
I haven't, but seems interesting. I'll check it out.
